### ISSUE TITLE
put paths and directory names in a config file?

### ISSUE THREAD

**Issue by cgosmeyer** [gbrammer/grizli#10]
From my experience with threedhst/unicorn, I would like to see all the paths and the directory names getting set in a config file.  That way I only need to remember to change that one config file if, for example, I prefer all my directory names to be lowercase, or I want to run tests using a different "RAW" directory.  In `prep.py`, for instance, I don't think `path="../RAW"` should be set to default within the code itself, but could be in a config.

**Comment by gbrammer** [comment]
This is now implemented with the `RAW_PATH=None, PREP_PATH=None, PERSIST_PATH=None, EXTRACT_PATH=None` parameters on `grizli.pipeline.auto_script.go`.  The `None` defaults initialize the previously-assumed structure based on the field root name:

```python
{home}
{home}/{root}
RAW_PATH = {home}/{root}/RAW
PREP_PATH = {home}/{root}/Prep
PERSIST_PATH = {home}/{root}/Persistence
EXTRACT_PATH = {home}/{root}/Extractions
```
