### ISSUE TITLE
Errors/issues with CFF file

### ISSUE THREAD

**Issue by augustfly** [gbrammer/grizli#137]
hey, if you review https://doi.org/10.5281/zenodo.7351572 and recent released versions on Zenodo you'll see three things that are related to the CFF file: 

1. All recent versions are the same on Zenodo. This is caused by the fact that the version key in the CFF file is stale and trumps the one encoded in the tagged release. 
2. All recent publication dates are the same. This is caused by the fact that the date key in the CFF file is stale and trumps the one encoded in the tagged release. 
3. On Zenodo there is no ORCID for recent deposits. That's because the ORCID field of 0000-0003-2680-0055 in the CFF file is not a valid ORCID value (we think yours should be 0000-0003-2680-005X instead). 

Per my discussions with Zenodo, they want to fix their CFF parsing to not use the author's CFF fields for version and date since those fields are automatically created in the release. The only way to prevent this issue right now is to remove those fields from the CFF. For the ORCID they are doing the right thing by rejecting the invalid ORCID. 

Unfortunately I don't think there's any automatic way to fix the Zenodo records other than logging in and updating their dates and versions to match the tagged releases (i.e., ex post facto).

It would be better to actually fix this for you, but this issue is the best I can do at the moment.

**Comment by gbrammer** [comment]
Thanks for the suggestion!  I was wondering why the versions weren't incrementing on zenodo with the new releases, so I'll try to edit the CFF file to fix this.

**Comment by gbrammer** [comment]
Confirmed that the zenodo versioning appears to be correct after removing the `version` and `date-released` tags from the CFF file.  Thanks again.
