### ISSUE TITLE
KeyError in Grizli-Pipeline?

### ISSUE THREAD

**Issue by flairue** [gbrammer/grizli#154]
Hi. I'm following the Grizli-Pipeline notebook, using the default files. I'm getting a KeyError during the autoscript.preprocess() step.

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[19], line 7
>       3 os.chdir(os.path.join(HOME_PATH, root, 'Prep'))
>       5 # This script will do all the preprocessing of the grism *and* imaging visits 
>       6 # found in your archive query.
> ----> 7 auto_script.preprocess(field_root=root, HOME_PATH=HOME_PATH,
>       8                        visit_prep_args=visit_prep_args, **preprocess_args)    
> 
> File /opt/anaconda3/envs/spiderweb/lib/python3.11/site-packages/grizli/pipeline/auto_script.py:1960, in preprocess(field_root, HOME_PATH, PERSIST_PATH, min_overlap, make_combined, catalogs, use_visit, master_radec, parent_radec, use_first_radec, skip_imaging, clean, skip_single_optical_visits, visit_prep_args, persistence_args)
>    1956 print('\n\n\n{0} radec: {1}\n\n\n'.format(direct['product'], radec))
>    1958 ###########################
>    1959 # Preprocessing script, background subtraction, etc.
> -> 1960 status = prep.process_direct_grism_visit(direct=direct, grism=grism,
>    1961                     radec=radec, skip_direct=False, **visit_prep_args)
>    1963 ###################################
>    1964 # Persistence Masking
>    1965 for file in direct['files']+grism['files']:
> 
> File /opt/anaconda3/envs/spiderweb/lib/python3.11/site-packages/grizli/prep.py:4543, in process_direct_grism_visit(direct, grism, radec, outlier_threshold, align_clip, align_thresh, align_mag_limits, align_rms_limit, align_triangle_ba_max, align_ref_border, align_min_flux_radius, align_assume_close, align_transform, align_guess, max_err_percentile, catalog_mask_pad, match_catalog_density, column_average, sky_iter, run_tweak_align, tweak_fit_order, skip_direct, fix_stars, tweak_max_dist, tweak_n_min, tweak_threshold, tweak_ref_exp, align_simple, single_image_CRs, skymethod, drizzle_params, iter_atol, static_mask, imaging_bkg_params, run_separate_chip_sky, separate_chip_kwargs, reference_catalogs, use_self_catalog, nircam_wisp_kwargs, oneoverf_kwargs, snowball_kwargs, angle_background_kwargs, miri_skyflat, miri_skyfile, use_skyflats)
>    4540         table_to_radec(cat[clip][so], f"{direct['product']}.cat.radec")
>    4542     if (fix_stars) & (not isACS) & (not isWFPC2) & (not isJWST):
> -> 4543         fix_star_centers(root=direct['product'], drizzle=False, 
>    4544                          mag_lim=19.5)
>    4546 #################
>    4547 # Grism image processing
>    4548 #################
>    4550 if skip_grism:
> 
> File /opt/anaconda3/envs/spiderweb/lib/python3.11/site-packages/grizli/prep.py:6153, in fix_star_centers(root, mag_lim, verbose, drizzle, cutout_size)
>    6151 wcs = []
>    6152 for i in range(N):
> -> 6153     flt = pyfits.open(sci[0].header['D{0:03d}DATA'.format(i+1)].split('[')[0], mode='update')
>    6154     # if True:
>    6155     #     flt = pyfits.open('../RAW/'+sci[0].header['D{0:03d}DATA'.format(i+1)].split('[')[0], mode='update')
>    6156     wcs.append(pywcs.WCS(flt[1], relax=True))
> 
> File /opt/anaconda3/envs/spiderweb/lib/python3.11/site-packages/astropy/io/fits/header.py:169, in Header.__getitem__(self, key)
>     166 else:
>     167     keyword = key
> --> 169 card = self._cards[self._cardindex(key)]
>     171 if card.field_specifier is not None and keyword == card.rawkeyword:
>     172     # This is RVKC; if only the top-level keyword was specified return
>     173     # the raw value, not the parsed out float value
>     174     return card.rawvalue
> 
> File /opt/anaconda3/envs/spiderweb/lib/python3.11/site-packages/astropy/io/fits/header.py:1819, in Header._cardindex(self, key)
>    1816         indices = self._rvkc_indices.get(keyword, None)
>    1818 if not indices:
> -> 1819     raise KeyError(f"Keyword {keyword!r} not found.")
>    1821 try:
>    1822     return indices[n]
> 
> KeyError: "Keyword 'D001DATA' not found."

Not sure what's wrong since I didn't edit anything. I tried using my own data (WFC3 image without grism) and encountered the same error.

**Comment by gbrammer** [comment]
Thanks for bringing that up.  I hadn't run the HST notebook in some time, and see that the `fix_star_centers` function is now broken. I just committed a https://github.com/gbrammer/grizli/pull/155 that turns that function off by default, so hopefully the script will be able to complete successfully.
