### ISSUE TITLE
Malloc errors in multifit.GroupFLT.compute_full_model

### ISSUE THREAD

**Issue by jensmelinder** [gbrammer/grizli#177]
With version 1.9.9 and using the NIRISS configuration files from 221215 (10.5281/zenodo.7628094) I get memory problems when trying to make the continuum models for grism data. In particular the problem appears when the config files are read inside `_compute_model`.

Loading the grism FLTs seems to work fine (`Load_GroupFLT`) which also reads in the config files. 

When reading the config files in `_compute_model` I first get a few different malloc errors:
`malloc(): invalid size (unsorted)`,
`python: malloc.c:4036: _int.malloc: Assertion '(unsigned long) (size) >= (unsigned long) (nb)' failed.`, and
`free(): invalid pointer`
The run the locks up completely (have let it run for 10+ hours).

I'm using a fairly powerful machine (64 cores, 512GB RAM), and have tried using different amounts of threads (from 4 to 20), and the same problem appears in all cases.

Using median subtraction (without a precomputed model) works fine. Any help with this would be appreciated.

**Comment by jensmelinder** [comment]
After looking at it some more I see that the config file reading is fine, the problems appear in `_compute_model_orders`.

**Comment by gbrammer** [comment]
I think this should be resolved with a bug I had found and fixed earlier today in https://github.com/gbrammer/grizli/commit/6389e939e3dc8cd24425624a4fd3e9449d1e0a55.

This isn't yet pushed to a new PyPI release, but can be installed from the repository with ``pip install git+https://github.com/gbrammer/grizli.git --upgrade``.

**Comment by jensmelinder** [comment]
Yes, that seems to have fixed the issue. And the prelim model subtraction before median option works really well as far as I can see.

**Comment by gbrammer** [comment]
OK, great.  Thanks for the feedback!
