### ISSUE TITLE
slit loss correction in the pipeline?

### ISSUE THREAD

**Issue by Vladan1986** [gbrammer/grizli#192]
Hello,

I have a question regarding the slit-loss corrections applied to the JWST spectra. I was wondering if (and how) the slit losses are addressed in your pipeline on the prism spectra.

According to what I found on the DAWN website regarding the data reduction (https://ui.adsabs.harvard.edu/abs/2023arXiv230600647H/abstract), the polynomial function was applied to correct for the slit-losses, but I am not sure if this is the case for the entire DAWN sample, or only for the sources mentioned in that work.

Thank you in advance.

Cheers,

**Comment by TheSkyentist** [comment]
I think this issue might be better raised on the [DJA github page](https://github.com/dawn-cph/dja), as it pertains to pipeline steps outside of `grizli`. I believe `grizli` is only used to generate the photometry on the corresponding NIRCam imaging which is then used as input to scale the spectroscopy.

**Comment by Vladan1986** [comment]
Thank you for your suggestion

Cheers,

**Comment by gbrammer** [comment]
See https://github.com/dawn-cph/dja/issues/21.  You can also file Issues / questions on the `msaexp` [module](https://github.com/gbrammer/msaexp/issues).
