### ISSUE TITLE
Update NIRCam LW bad pixel masks 

### ISSUE THREAD

**Issue by chriswillott** [gbrammer/grizli#200]
Using science data from 26th December 2023 I have identified new hot pixels on the NIRCam LW detectors. Most of these pixels are hot in all observations I looked at, but about 20% are intermittent. Since the number is very small I would mask all of them for the future.
The attached lists give the x, y detector positions (0-indexed) for each LW detector.

[badpixlist_along_20240108.txt](https://github.com/gbrammer/grizli/files/13878784/badpixlist_along_20240108.txt)
[badpixlist_blong_20240108.txt](https://github.com/gbrammer/grizli/files/13878785/badpixlist_blong_20240108.txt)

**Comment by gbrammer** [comment]
Added in [v1.11](https://github.com/gbrammer/grizli/releases/tag/1.11) release.
