### ISSUE TITLE
rnoise_percentile not passed from aws.visit_processor.cutout_mosaic to utils.drizzle_from_visit

### ISSUE THREAD

**Issue by chriswillott** [gbrammer/grizli#202]
The parameter rnoise_percentile can be set in aws.visit_processor.cutout_mosaic, but it is not passed to utils.drizzle_from_visit so it is always set to the default value of 99.

**Comment by gbrammer** [comment]
Thanks @chriswillott .  I pushed a fix in https://github.com/gbrammer/grizli/pull/208, which is available in the master branch but not yet in the pip release.

**Comment by gbrammer** [comment]
This is now in the release, closing.
