### ISSUE TITLE
Installation Issues, error importing disperse

### ISSUE THREAD

**Issue by amn3142** [gbrammer/grizli#21]
Installing the latest version of grizli on my new machine. Running python 2.7.14, newest version of astroconda, operating system CentOS 7.

After installing grizli using the installation script (with the fix noted in the previous issue report), starting a python session and importing grizli yields the following error:

```
Python 2.7.14 |Anaconda, Inc.| (default, Oct 13 2017, 10:47:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grizli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/grizli/grizli/__init__.py", line 17, in <module>
    from . import utils_c
  File "/opt/grizli/grizli/utils_c/__init__.py", line 7, in <module>
    from . import disperse
ImportError: cannot import name disperse

```
I have verified that I have cython installed, so I'm not sure why it's not picking up the name disperse.pyx/ disperse.c, although I don't really know how these things work.

**Comment by gbrammer** [comment]
@amn3142 Were you trying to `import grizli` in the repository directory?  That error can happen there so try importing from somewhere else, e.g., `$HOME`.

**Comment by amn3142** [comment]
@gbrammer I get the same error when trying to import in $HOME

**Comment by amn3142** [comment]
@gbrammer update: Installed minconda2 (rather than anaconda2), downgraded to python 2.7.12 which is the verified version in your installation instructions, but am still receiving the same error.

**Comment by amn3142** [comment]
@gbrammer Changed __init__.py to

import disperse
import interp

Now I am able to import grizli, and it seems to be functioning correctly. Not sure if this will mess something else up... but it seems ok.

**Comment by amn3142** [comment]
Built the latest version of grizli, and no longer having this issue. The gremlins must have been appeased.
