### ISSUE TITLE
Fetch calib needs to include the pixel area map.

### ISSUE THREAD

**Issue by julesfowler** [gbrammer/grizli#22]
The `grizli.utils.fetch_default_calib/config` needs to pull in `ir_wfc3_map.fits`. 
`MultiBeam` is looking for it and sadly coming up short.

**Comment by gbrammer** [comment]
Added with https://github.com/gbrammer/grizli/commit/06b2bb1a51cc4090eb57f37798a4b6cb6b24b2c2.
