### ISSUE TITLE
Cycle 2 darks update to NIRCam Long Wave bad pixel masks 

### ISSUE THREAD

**Issue by chriswillott** [gbrammer/grizli#233]
Using full-frame darks from Cycle 2 program 4442 taken between November 2023 and June 2024 and science data from program 3362 taken in May 2024 I have identified new hot pixels on the NIRCam LW detectors. 
There are 1969 new hot pixels in module A and 1458 in module B when compared to the grizli bad pixel masks nrc_badpix_240112_NRC?LONG.fits.gz.
The attached lists give the x, y detector positions (0-indexed) of the new hot pixels for each LW detector.

**Comment by chriswillott** [comment]
[
[badpixlist_along_20240626.txt](https://github.com/user-attachments/files/15995936/badpixlist_along_20240626.txt)
](url)

[badpixlist_blong_20240626.txt](https://github.com/user-attachments/files/15995938/badpixlist_blong_20240626.txt)

**Comment by gbrammer** [comment]
Thanks @chriswillott! I added these at https://github.com/gbrammer/grizli/pull/234 and bumped [grizli=1.11.10](https://github.com/gbrammer/grizli/releases/tag/1.11.10)

Do you have a notebook you'd be willing to share and attach to this Issue that can be used to reproduce the bpix list and extend it in the future?  It doesn't have to work out of the box, but just to demonstrate the methodology.  

If you commit a trivial change and push it in a PR, you'll be more formally recognized as a [Contributor](https://github.com/gbrammer/grizli/graphs/contributors) to the grizli repo.  Perhaps just a comment like `# 240627 LW bad pixels from C. Willott` here:
https://github.com/gbrammer/grizli/blob/4df3b14281e1fdd162a6ead5aad9287169335f19/grizli/utils.py#L7725-L7726
