### ISSUE TITLE
Adding CI's for 3.11 and 3.12

### ISSUE THREAD

**Issue by TheSkyentist** [gbrammer/grizli#237]
Raising this issue wondering if it's worth adding Python 3.11 and 3.12 to grizli CI tests. I've been consistently running grizli under Python 3.12 ever since the most recent Drizzlepac releases. I believe the support under these Python versions is there, it would be great to make that explicit in the documentation and add CI tests. I'm happy to make a PR if this would be useful. 

I actually haven't run the latest versions of grizli under Python <3.10. But it's good to have the CI tests to validate that grizli can still run under these environments. For example I don't believe that the JWST pipeline supports Python <3.10, so I doubt grizli[jwst] would.

**Comment by gbrammer** [comment]
Yes, I think it should be fine to add CI test builds for the newer versions.  I generally use 3.10 myself.

**Comment by TheSkyentist** [comment]
Addressed via #238
