### ISSUE TITLE
issue with AstrometryDB in process_direct_grism_visit

### ISSUE THREAD

**Issue by RaymondSimons** [gbrammer/grizli#27]
I'm finding an issue with the astrometry update in process_direct_grism_visit. I believe this is related to the stwcs AstrometryDB database.

If off the STScI network, AstrometryDB is inaccessible. This appears to be addressed here: https://github.com/spacetelescope/stwcs/issues/61

In this case, process_direct_grism_visit does not crash, but the following warnings are recorded in astrodrizzle.log:

> [WARNING ] WARNING : AstrometryDB service inaccessible!
> [WARNING ]     AstrometryDB called: https://mastdev.stsci.edu/portal/astrometryDB/
> [INFO    ] Updating astrometry for icxt53ifq
> [WARNING ] AstrometryDB not available.
> [WARNING ] NO Updates performed for icxt53ifq
> [WARNING ] Problems getting solutions from database
> [WARNING ]  NO Updates performed for icxt53ifq

If on the STScI network, AstrometryDB can be accessed. However, (in all cases that I've tested) process_direct_grism_visit crashes because no solution is found in the database:

>    166         # take inventory of what hdrlets are already appended to this file
>     167         hdrnames = headerlet.get_headerlet_kw_names(fileobj, 'hdrname')
> --> 168         headerlets, best_solution_id = self.getObservation(observationID)
>     169         if headerlets is None:
>     170             logger.warning("Problems getting solutions from database")
> 
> /anaconda2/envs/grizli-dev/lib/python3.5/site-packages/stwcs/updatewcs/astrometry_utils.py in getObservation(self, observationID)
>     331                 serviceEndPoint = self.serviceLocation + \
>     332                     'observation/read/' + observationID + \
> --> 333                     '?wcsname='+solutionID
>     334                 r_solution = requests.get(serviceEndPoint, headers=headers)
>     335                 if r_solution.status_code == requests.codes.ok:
> 
> TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by gbrammer** [comment]
@RaymondSimons: I've noticed that error go by, but I've always ignored it since it doesn't cause a crash for me.  I'm testing setting "use_db" in the call to updatewcs.updatewcs and if it goes through OK I'll push the change.

**Comment by gbrammer** [comment]
I should say, `use_db=False`.

**Comment by gbrammer** [comment]
Fixed in https://github.com/gbrammer/grizli/pull/28
