### ISSUE TITLE
RecursionError when installing standalone drizzle

### ISSUE THREAD

**Issue by gnoir0t** [gbrammer/grizli#32]
You may encounter a `RecursionError` when installing drizzle using the conda environment [installation of grizli](https://grizli.readthedocs.io/en/master/grizli/install.html#installation-with-a-conda-environment).

If this happens, check your current version of the `sphinx` python package (e.g., `pip show sphinx`), and downgrade it to version 1.5.6 if your current version is higher than that (e.g., `pip install sphinx==1.5.6`). Installation of drizzle should then work.

Stackoverflow [link](https://stackoverflow.com/questions/53117828/pip-installation-causes-recursionerror) related to the issue.

**Comment by gbrammer** [comment]
I've now pulled out the calls to the standalone drizzle module, so `grizli` should just use `drizzlepac` throughout as installed with the `environment_min.yml` file.
