### ISSUE TITLE
Cannot import name 'splmake'

### ISSUE THREAD

**Issue by bkornpob** [gbrammer/grizli#39]
Hi,

I followed the installation guide from the grizli.readthedocs.io, and tried to run  Grizli-Pipline.ipynb. The pipeline shows an error at cell 35 (right after 'Parameters for object fitting') saying "ImportError: cannot import name 'splmake'." I think the reasons is that scipy.interpolate.splmake has been deprecated (http://pageperso.lif.univ-mrs.fr/~francois.denis/IAAM1/scipy-html-1.0.0/generated/scipy.interpolate.splmake.html).

**Comment by gbrammer** [comment]
This should be resolved in a fresh environment with up-to-date dependencies.
