### ISSUE TITLE
Does the reported OIII flux corresponds to OIII5007+4959?

### ISSUE THREAD

**Issue by albertfxwang** [gbrammer/grizli#40]
I have a question regarding the OIII flux reported in the header of *.full.fits[0]. Does this value correspond to OIII5007 only or both OIII doublets?

I notice that `grizli.multifit.MultiBeam.drizzle_fit_lines` subtracts the OIII4959 contamination from OIII5007 with the following code:
```
                        if (line == 'OIII') & ('cfit' in fit) & mask_4959:
                            lm = t_o3['line OIII-4959']
                            scl = fit['cfit']['line OIII'][0]/(1+z_driz)
                            scl *= 1./(2.98+1)
                            sp = [lm.wave*(1+z_driz), lm.flux*scl]

                            m = beam.compute_model(spectrum_1d=sp, 
                                                   in_place=False,
                                                   is_cgs=True) 
                                                   
                            lcontam = m.reshape(beam.beam.sh_beam)
                            lcontam *= pscale_array
                            beam.extra_lines += lcontam
```
where we see that it's making a 2D model of OIII4959 and add that to the beam contamination. However, the flux normalization factor `scl` is calculated such that the value of `fit['cfit']['line OIII'][0]` corresponds to the sum of both OIII doublets, instead of being just the OIII5007 flux. The results of `fit['cfit'][line ...]` will be passed on to the header of the multiple extensions of the  final *full.fits file. So I'm wondering if the reported OIII flux is actually 4/3. * OIII5007 flux?

**Comment by gbrammer** [comment]
The reported line fluxes derived from the template fit are the sum 4959+5007, and 4959 is subtracted in the drizzled line map assuming a fixed ratio 4959:5007 = 1:2.98.

**Comment by albertfxwang** [comment]
Thanks Gabe for the quick reply! I also notice that the treatment of OIII4959 contamination is a bit different than that of other contaminating lines. In addition to subtracting the best-fit model line flux from `beam_data` in `grizli.multifit.drizzle_to_wavelength`, there's also procedures to downweight the pixels affected by the contaminations, i.e. the following code in `grizli.multifit.MultiBeam.drizzle_fit_lines`:
```
                                if line_flux > 0:
                                    extra_msk = lcontam > mask_sn_limit*lmodel
                                    extra_msk &= (lcontam > 0)
                                    extra_msk &= (lmodel > 0)
                                    beam.ivar[extra_msk] *= 0
```
It seems that this procedure is not done for the subtraction of OIII4959. Do you think this might result in under-estimating the uncertainties in the outer regions of the drizzled line maps where OIII5007 flux from the spatial outer regions might be smaller than the OIII4959 flux from the spatial central regions of the galaxy? I'm really eager to learn about your ideas.

**Comment by gbrammer** [comment]
Yes, you're right that the code can subtract [OIII]4959 from the [OIII] doublet line map, but that it doesn't include the spatial location of [OIII]4959 in the line map mask.  If you had many PAs to choose from, I agree that it could be nice to try to mask [OIII]4959.  However, the `extra_msk = lcontam > mask_sn_limit*lmodel` algorithm is already a bit of a hack and might not give the most robust results.   To try to use the masking with the code as-is, the following might work:

```python
import copy

templ = ... # template dictionary including 'OIII' doublet
tfit = mb.template_at_z(z, templates=templ)

tspl = copy.deepcopy(tfit)

# version of the fit splitting the doublet with forced line ratio
cfit = tspl['cfit']
oiii = cfit['line OIII'] # 4959+5007 doublet flux, uncertainty
cfit['line OIII-4959'] = [v*scl for v, scl in zip(oiii, [1./3.98, 1])]
cfit['line OIII-5007'] = [v*scl for v, scl in zip(oiii, [2.98/3.98, 1])]

cfit.pop('line OIII')
tspl['cfit'] = cfit

# Need 1D templates in 'templates' key
to3 = utils.load_templates(fwhm=100, line_complexes=False, stars=False, full_line_list=['OIII-4959', 'OIII-5007'], continuum_list=[], fsps_templates=False, alf_template=True, lorentz=False)
for tn in to3:
    tspl['templates'][tn] = tsplit[tn]
    
hdu = mb.drizzle_fit_lines(tspl, pline, force_line=[..., 'OIII-5007'], ...)
```

**Comment by albertfxwang** [comment]
Thanks so much Gabe for your detailed reply. This is really helpful and I will report how this code snippet works.
