### ISSUE TITLE
Value Error in Fine Alignment w/ Grizli-Pipeline

### ISSUE THREAD

**Issue by jrcooper91** [gbrammer/grizli#46]
During Fine Alignment to GAIA DR2 in Grizli-Pipeline.ipynb (Demo & own data):

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-be6ef856b566> in <module>
     10 
     11     out = auto_script.fine_alignment(field_root=root, HOME_PATH=HOME_PATH, 
---> 12                                      **fine_alignment_args)
     13 
     14     # Update headers with the result from the fine alignment

~/anaconda3/lib/python3.7/site-packages/grizli-1.0.dev1450-py3.7-macosx-10.7-x86_64.egg/grizli/pipeline/auto_script.py in fine_alignment(field_root, HOME_PATH, min_overlap, stopme, ref_err, radec, redrizzle, shift_only, maglim, NITER, catalogs, method, radius, program_str, match_str, all_visits, date, gaia_by_date, tol, fit_options, print_options)
   2883     pi = p0*1.#*10.
   2884     for iter in range(NITER):
-> 2885         fit = minimize(_objfun_align, pi*pscl, args=fit_args, method=method, jac=None, hess=None, hessp=None, bounds=None, constraints=(), tol=tol, callback=None, options=fit_options)
   2886         pi = fit.x.reshape((-1,len(pscl)))/pscl
   2887 

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    598         return _minimize_neldermead(fun, x0, args, callback, **options)
    599     elif meth == 'powell':
--> 600         return _minimize_powell(fun, x0, args, callback, **options)
    601     elif meth == 'cg':
    602         return _minimize_cg(fun, x0, args, jac, callback, **options)

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/optimize.py in _minimize_powell(func, x0, args, callback, xtol, ftol, maxiter, maxfev, disp, direc, return_all, **unknown_options)
   2629         direc = asarray(direc, dtype=float)
   2630 
-> 2631     fval = squeeze(func(x))
   2632     x1 = x.copy()
   2633     iter = 0

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    325     def function_wrapper(*wrapper_args):
    326         ncalls[0] += 1
--> 327         return function(*(wrapper_args + args))
    328 
    329     return ncalls, function_wrapper

~/anaconda3/lib/python3.7/site-packages/grizli-1.0.dev1450-py3.7-macosx-10.7-x86_64.egg/grizli/pipeline/auto_script.py in _objfun_align(p0, tab, ref_tab, ref_err, shift_only, ret)
   3790 
   3791     # Residuals
-> 3792     dr = np.sqrt(np.hstack(dx)**2+np.hstack(dy)**2)
   3793 
   3794     if ret == 'huber': # Minimize Huber loss function

~/anaconda3/lib/python3.7/site-packages/numpy/core/shape_base.py in hstack(tup)
    338         return _nx.concatenate(arrs, 0)
    339     else:
--> 340         return _nx.concatenate(arrs, 1)
    341 
    342 

ValueError: need at least one array to concatenate

The wcs.log file doesn't seem to be finding sources as the output from 
!grep " 0 " `ls -ltr *wcs.log | awk '{print $9}'` | sed "s/  */ /g"

> 0 0.0000 0.0000 0.0000 1.00000 0.000 2

**Comment by gbrammer** [comment]
I'm going to close this since the demo runs OK with the latest code.  Please resubmit if you still find the problem with the alignment.
