### ISSUE TITLE
problem installing grizli on python 3.6.12

### ISSUE THREAD

**Issue by Vince-ec** [gbrammer/grizli#50]
recently upgraded to python 3.6.12, but when I went to install grizli I got the following error:

C extension: .pyx
/Users/Vince.ec/miniconda3/envs/astroconda3.6/lib/python3.6/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.2dev1647' to '1.2.dev1647'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
writing grizli.egg-info/PKG-INFO
writing dependency_links to grizli.egg-info/dependency_links.txt
writing requirements to grizli.egg-info/requires.txt
writing top-level names to grizli.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching 'grizli/tests/coveragerc'
warning: no files found matching '*.pxd' under directory 'grizli'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching 'astropy_helpers/ez_setup.py'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.rst' under directory 'astropy_helpers/astropy_helpers'
no previously-included directories found matching 'astropy_helpers/build'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'grizli.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
building 'grizli.utils_c.interp' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Vince.ec/miniconda3/envs/astroconda3.6/include -arch x86_64 -I/Users/Vince.ec/miniconda3/envs/astroconda3.6/include -arch x86_64 -I/Users/Vince.ec/miniconda3/envs/astroconda3.6/lib/python3.6/site-packages/numpy/core/include -I/Users/Vince.ec/miniconda3/envs/astroconda3.6/include/python3.6m -c grizli/utils_c/interp.c -o build/temp.macosx-10.9-x86_64-3.6/grizli/utils_c/interp.o
In file included from /opt/local/lib/gcc49/gcc/x86_64-apple-darwin15/4.9.4/include-fixed/syslimits.h:7:0,
                 from /opt/local/lib/gcc49/gcc/x86_64-apple-darwin15/4.9.4/include-fixed/limits.h:34,
                 from /Users/Vince.ec/miniconda3/envs/astroconda3.6/include/python3.6m/Python.h:11,
                 from grizli/utils_c/interp.c:26:
/opt/local/lib/gcc49/gcc/x86_64-apple-darwin15/4.9.4/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by gbrammer** [comment]
@Vince-ec That doesn't look like grizli's problem.  The [offending line](https://github.com/gbrammer/grizli/blob/master/grizli/utils_c/interp.c#L26) in the auto-generated c file is ``#include "Python.h"``.  While it works, I never understood how grizli could compile without ``cython``.  You could try installing ``cython`` manually before trying to compile grizli, since there is [logic in setup.py](https://github.com/gbrammer/grizli/blob/master/setup.py#L19) to compile differently with or without it.

**Comment by Vince-ec** [comment]
@gbrammer I got it installed after updating all my macports stuff, I'm not sure what the issue was exactly but its working now.
