### ISSUE TITLE
prospector required when running grizli.fitting.run_all()

### ISSUE THREAD

**Issue by jkmatharu** [gbrammer/grizli#53]
Fits and plots are produced, but raises a Module Not Found Error. Code breaks at line 592 in `full_sed_plot()`

`import prospect.utils.smoothing`

Perhaps include prospector + its dependencies as part of grizli installation

**Comment by gbrammer** [comment]
Ah, right.  That's a requirement for making the plots after the photometry + spectra fits.  I've added it to ``requirements.txt``.

**Comment by jkmatharu** [comment]
I had to also do pip install `astro-sedpy` to make it work... but that's technically a requirement for `astro-prospector`.

**Comment by gbrammer** [comment]
Yes, that's also now included in  [requirements.txt](https://github.com/gbrammer/grizli/blob/master/requirements.txt#L30).  I'm going to close this PR but please let me know if any other issues come up.
