### ISSUE TITLE
ACS CONFIG tar.gz file not opening

### ISSUE THREAD

**Issue by jkmatharu** [gbrammer/grizli#63]
Hi Gabe,

Trying to reduce some overlapping ACS data with a 3D-HST field with Grizli. Downloaded the ACS files by setting ACS=True in both `grizli.utils.fetch_default_calibs` and `grizli.utils.fetch_config_files`. ACS_CONFIG.tar.gz and ACS.WFC.sky.tar.gz  will not unzip, with error:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by gbrammer** [comment]
There was a problem with the place I was hosting the config files for download.   I just created a new repository ([grizli-config](https://github.com/gbrammer/grizli-config)) for them that should hopefully be more permanent and updated `utils.py` (https://github.com/gbrammer/grizli/commit/5bde842e3cb0822d8295d037886c0fee1de6a88d) to point to them.
