### ISSUE TITLE
Using MIRAGE simulation products with Grizli

### ISSUE THREAD

**Issue by jkmatharu** [gbrammer/grizli#64]
Hi Gabe,

I'm attempting to run some MIRAGE simulation products through Grizli of NIRCAM WFSS. I have NIRISS grizli config files but not NIRCAM ones. Tried to use the same method of download as I used for the NIRISS ones, but it doesn't seem to work. Do these exist, and is it possible to use MIRAGE data products with Grizli (I'm following an old python notebook of yours that did this for fake NIRISS data).

**Comment by gbrammer** [comment]
I put the jwst config files at https://github.com/gbrammer/grizli-config/blob/main/jwst-grism-conf.tar.gz, which is also now a more stable link for finding the other config files.
