### ISSUE TITLE
UVIS config files

### ISSUE THREAD

**Issue by jkmatharu** [gbrammer/grizli#65]
Hi Gabe,

I have overlapping UVIS data with a 3D-HST field I'm trying to reduce as part of a Grizli reduction/extraction. Is it possible to reduce it? There doesn't seem to be any WFC3/UVIS config files in the CONF folder and there doesn't seem to be an e.g.  `UVIS=True` argument we can use with `grizli.utils.fetch_config_files.`

**Comment by mberg3** [comment]
Hi @jkmatharu,

I was never able to fully extract a spectrum with grizli for UVIS. (It extracted something, but it wasn't right.) I ended up using grizli to produce the drizzled G280 and direct images and the cosmic ray cleaned exposures. For the extraction, I used the XIDL code (https://github.com/profxj/xidl/tree/master/HST/WFC3/G280). However, I'm new to slitless spectroscopy. I've added in the UVIS info everywhere I think it goes into my forked version. If you are more experienced with grizli/grism spectroscopy, you might have better luck getting the extraction working.
