### ISSUE TITLE
Change calculation of shapes of images for JWST/HST

### ISSUE THREAD

**Issue by victoriastrait** [gbrammer/grizli#75]
- make variables for science extensions e.g., when calculating shape in prep (line 4642):

if isJWST:
    sci_ext = 1
else:
    sci_ext = 0
sh = im[sci_ext].data.shape
data = im[sci_ext].dat.flatten() / flat

- instead of "ifJWST", check instrument and set the shape (prep line 4812)

if _instrument in ['NIRISS', 'NIRCAM']:

**Comment by gbrammer** [comment]
The logic at https://github.com/gbrammer/grizli/blob/master/grizli/prep.py#L4639 should now handle JWST / not JWST in the sky background images.
