### ISSUE TITLE
TypeError when running set_jwst_to_hst_keywords outside of normal grizli workflow

### ISSUE THREAD

**Issue by pascaloesch** [gbrammer/grizli#85]
Running `jwst_utils.set_jwst_to_hst_keywords` outside of the grizli workflow runs into a TypeError as `initialize_jwst_image` returns a boolean and not the image. A possible fix is to reopen the image after the jwst image is initialized.
`    if 'OTELESCO' not in img[0].header:
        OK = initialize_jwst_image(input, verbose=verbose) # this returns a bool, not img
        # now need to reopen image
        if isinstance(input, str):
            img = pyfits.open(input, mode='update')
        else:
            img = input`

**Comment by gbrammer** [comment]
Thanks @pascaloesch .  This should now be fixed in https://github.com/gbrammer/grizli/commit/205959a6cb993b750be5b565ce5521d7a734d757.
